FROM python:3.9-slim

WORKDIR /app

# Copy specific folders
COPY data/ /app/data
COPY models/ /app/models
COPY config/ /app/config
COPY src/ /app/src
COPY main_train.py /app/main_train.py
COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install -r requirements.txt

# Create logs folders
RUN mkdir -p logs

EXPOSE 8000
CMD ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "8000"]
