# Use an official Python runtime as a parent image
FROM python:3.9-slim

WORKDIR /app

# Copy specific folders
COPY data/ /app/data
COPY models/ /app/models
COPY config/ /app/config
COPY src/ /app/src
COPY main_train.py /app/main_train.py
COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install -r requirements.txt

# Create logs and results folders
RUN mkdir -p logs results

# Run the training script
CMD ["python", "main_train.py"]